# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AniTrack < Formula
  desc ""
  homepage "https://github.com/rinem/ani-track"
  version "0.2"

  on_macos do
    url "https://github.com/rinem/ani-track/releases/download/v0.2/ani-track_0.2_darwin_all.tar.gz"
    sha256 "75f49e91f6d5b28a5528d32590a458822cdf3395df0567895d6137e2722fa6fe"

    def install
      bin.install "ani-track"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rinem/ani-track/releases/download/v0.2/ani-track_0.2_linux_arm64.tar.gz"
      sha256 "eb6a7d672b664b6b9bcfcd34e03af8629783fdff6f44033ded01533ede5c8677"

      def install
        bin.install "ani-track"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rinem/ani-track/releases/download/v0.2/ani-track_0.2_linux_amd64.tar.gz"
      sha256 "bbbd76390355475fe14cfaea155ae3c36ed6b186a7ebf6ef7db41c4fc4cb0e07"

      def install
        bin.install "ani-track"
      end
    end
  end
end
